version: "3.8"

services:
    postgres:
        image: postgres:15
        container_name: postgres_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: agregator
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis:7
        container_name: redis_cache
        command: ["redis-server", "--requirepass", "root"]
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

    adminer:
        image: adminer
        ports:
            - "8080:8080"
        depends_on:
            - postgres

volumes:
    postgres_data:
    redis_data:
