export const TMDBSearchMockData = [
    {
        adult: false,
        backdrop_path: "/eU7IfdWq8KQy0oNd4kKXS0QUR08.jpg",
        genre_ids: [878, 12, 28],
        id: 1061474,
        original_language: "en",
        original_title: "Superman",
        overview:
            "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
        popularity: 982.6107,
        poster_path: "/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg",
        release_date: "2025-07-09",
        title: "Superman",
        video: false,
        vote_average: 7.6,
        vote_count: 2356,
    },
    {
        adult: false,
        backdrop_path: "/5PfHGXosySGs0l1JfeREspy3v6G.jpg",
        genre_ids: [878, 28, 12],
        id: 1924,
        original_language: "en",
        original_title: "Superman",
        overview:
            "Mild-mannered Clark Kent works as a reporter at the Daily Planet alongside his crush, Lois Lane. Clark must summon his superhero alter-ego when the nefarious Lex Luthor launches a plan to take over the world.",
        popularity: 12.5819,
        poster_path: "/d7px1FQxW4tngdACVRsCSaZq0Xl.jpg",
        release_date: "1978-12-14",
        title: "Superman",
        video: false,
        vote_average: 7.2,
        vote_count: 4039,
    },
    {
        adult: false,
        backdrop_path: null,
        genre_ids: [28, 12, 878],
        id: 167595,
        original_language: "hi",
        original_title: "Superman",
        overview:
            "In this Indian take on the classic superhero story, a young baby from the doomed planet Krypton is sent to Earth, where he is adopted by an elderly couple in India who name him Shekhar. After growing to an adult and learning about his origins and powers, he goes to the city in search of his school sweetheart, Gita, who has become a newpaper reporter. At the same time, Verma, Shekhar's rival for Gita's affection in their school days, has gone on to become a crime lord and general super-villain. Verma has hatched at plan to become rich by devastating part of India with natural disasters, then buying up all of the abandoned land. Will Superman/Shekhar be able to put a stop to Verma's evil plan? Will he win Gita's heart? Will he keep his double identity a secret?",
        popularity: 0.587,
        poster_path: "/xC7uUL6liwvkATfYs89Ag5TqW3O.jpg",
        release_date: "1987-12-31",
        title: "Superman",
        video: false,
        vote_average: 4.7,
        vote_count: 16,
    },
    {
        adult: false,
        backdrop_path: "/6PCprqrm0kdzYdAtZlSiFoY0Ypi.jpg",
        genre_ids: [28, 16, 10751, 12, 878, 14],
        id: 95414,
        original_language: "en",
        original_title: "Superman",
        overview:
            "After The Daily Planet receives a letter from a mad scientist threatening to wreak destruction with his Electrothanasia Ray, Lois Lane heads out in the hopes of getting more information for a news story.",
        popularity: 1.1915,
        poster_path: "/4DK6wWZTp6v32NUXszkHOPGxm16.jpg",
        release_date: "1941-09-26",
        title: "Superman",
        video: false,
        vote_average: 6.886,
        vote_count: 110,
    },
    {
        adult: false,
        backdrop_path: "/jDW24Hswd1gCHqmPUxf32E2K3yY.jpg",
        genre_ids: [28],
        id: 558077,
        original_language: "bn",
        original_title: "Superman",
        overview:
            "A child from a dying world is sent to Earth, where his alien physiology renders him superhuman. Bengali remake of the 1978 classic.",
        popularity: 0.4549,
        poster_path: "/deA1k1ZnenD9zdm2deoXgbnZo7n.jpg",
        release_date: "1990-01-01",
        title: "Superman",
        video: false,
        vote_average: 7.4,
        vote_count: 6,
    },
    {
        adult: false,
        backdrop_path: "/sfWWu2Nf6FuGinullL4FD1QldnW.jpg",
        genre_ids: [28, 80, 878],
        id: 126712,
        original_language: "en",
        original_title: "Superman",
        overview:
            "Superman comes to Earth as a child and grows up to be his home's first superhero with his first major challenge being to oppose The Spider Lady.",
        popularity: 1.1959,
        poster_path: "/vLvSA6HLaldOBOCeKw8jJejXV8J.jpg",
        release_date: "1948-07-15",
        title: "Superman",
        video: false,
        vote_average: 6.017,
        vote_count: 29,
    },
    {
        adult: false,
        backdrop_path: null,
        genre_ids: [],
        id: 1069657,
        original_language: "hi",
        original_title: "Superman",
        overview:
            "A scientist, whose daughter had died at the hands of a gangster, creates a serum that will give a person superhuman powers. His adopted daughter uses the serum to battle a gang that threatens to take over the city.",
        popularity: 1.4561,
        poster_path: "/qIg5Yvu70U7Jrtmd0zEsOWEYHLV.jpg",
        release_date: "1960-01-01",
        title: "Superman",
        video: false,
        vote_average: 7.2,
        vote_count: 2,
    },
    {
        adult: false,
        backdrop_path: null,
        genre_ids: [16, 28, 878],
        id: 974593,
        original_language: "ja",
        original_title: "超人ロック 新世界戦隊",
        overview:
            "Azalea has been residing on the Colony-Planet of Dinahl, and she can't recall anything about herself until she hears a voice calling her name. Then there is another voice summoning her to go to a park on top of a skyscraper. Once she arrives there, she meets up with other people who also have no recollection of who they are or what they were doing before arriving at this destination as instructed by the voice. All the people assembled there possess superhuman powers, such as Eno's psychic power, Umoth's x-ray vision, Neia's teleportation powers, Azalea's telepathy, and Locke's electrical wizardry. Who has summoned them, and what will the five super-psychics confront?",
        popularity: 1.2781,
        poster_path: "/hrMHFVm1WMnFKmASlQPUVGwkOS6.jpg",
        release_date: "1991-08-22",
        title: "Locke the Superman: New World Command",
        video: false,
        vote_average: 8.5,
        vote_count: 2,
    },
    {
        adult: false,
        backdrop_path: "/doiUtOHzcxXFl0GVQ2n8Ay6Pirx.jpg",
        genre_ids: [28, 12, 14],
        id: 209112,
        original_language: "en",
        original_title: "Batman v Superman: Dawn of Justice",
        overview:
            "Fearing the actions of a god-like Super Hero left unchecked, Gotham City’s own formidable, forceful vigilante takes on Metropolis’s most revered, modern-day savior, while the world wrestles with what sort of hero it really needs. And with Batman and Superman at war with one another, a new threat quickly arises, putting mankind in greater danger than it’s ever known before.",
        popularity: 19.767,
        poster_path: "/5UsK3grJvtQrtzEgqNlDljJW96w.jpg",
        release_date: "2016-03-23",
        title: "Batman v Superman: Dawn of Justice",
        video: false,
        vote_average: 5.984,
        vote_count: 18438,
    },
    {
        adult: false,
        backdrop_path: "/aQrovkyyX6GBu8S0nzzmourACAp.jpg",
        genre_ids: [28],
        id: 451492,
        original_language: "cn",
        original_title: "香港超人大破摧花黨",
        overview: "Hong Kong Superman is a Hong Kong Martial Arts movie.",
        popularity: 0.8159,
        poster_path: "/es8aNWv11c0XTGhagqmHSewoXvz.jpg",
        release_date: "1975-06-25",
        title: "Hong Kong Superman",
        video: false,
        vote_average: 7.5,
        vote_count: 2,
    },
    {
        adult: false,
        backdrop_path: null,
        genre_ids: [18],
        id: 148918,
        original_language: "ro",
        original_title: "Superman, Spider-Man sau Batman",
        overview:
            "Aron, a 5-year-old boy, sets together with his worried father on a journey at the end of which he wishes, like the superheroes in the comic books, to save his mother suffering from a heart condition.",
        popularity: 0.7059,
        poster_path: "/iUp85s5s7eaPbuCUNqOCeJCEVpY.jpg",
        release_date: "2011-06-01",
        title: "Superman, Spider-Man or Batman",
        video: false,
        vote_average: 6.9,
        vote_count: 23,
    },
    {
        adult: false,
        backdrop_path: "/19RxQgzL8WHTtcG9Nrv2hKVSrTq.jpg",
        genre_ids: [16, 878],
        id: 123951,
        original_language: "ja",
        original_title: "超人ロック",
        overview:
            'When the villainous Lady Kahn starts building an army of super-powerful espers, Colonel Ryu Yamaki is dispatched to recruit the most powerful superhuman in the known universe to help oppose her. Unfortunately, the esper known only as Locke has either never heard the "with great powers come great responsibilities" speech or he simply doesn\'t care, and he refuses to leave his peaceful civilian life herding sheep.  However, when Lady Kahn makes a preemptive move to take Locke and Ryu out of the picture, the irritated superbeing quickly changes his mind. Now the bad guys are about to learn that starting a fight with someone with super powers that include teleportation, a nearly indestructible force field and space martial arts was a very big mistake!',
        popularity: 1.3104,
        poster_path: "/bhjHuyRBocTkJPd3lIewmDH0jg3.jpg",
        release_date: "1984-03-11",
        title: "Locke the Superman",
        video: false,
        vote_average: 6.5,
        vote_count: 9,
    },
    {
        adult: false,
        backdrop_path: null,
        genre_ids: [],
        id: 570716,
        original_language: "en",
        original_title: "Superman: Requiem",
        overview:
            "Superman is the world's greatest super hero, and law enforcement across the globe has come to rely on him to deal with some of the major tasks that face society. When the Man of Steel loses some of his powers after an evil villain attacks him with Kryptonite though, he must overcome his obstacles and prove he really is a super man.",
        popularity: 0.7609,
        poster_path: "/gtbdkohBZYx9aNIhdjI8k7SiKge.jpg",
        release_date: "2011-11-07",
        title: "Superman: Requiem",
        video: false,
        vote_average: 4.1,
        vote_count: 4,
    },
    {
        adult: false,
        backdrop_path: "/n2Jc6GF6xEX2AgojziYAR1aFc0w.jpg",
        genre_ids: [878, 28, 27],
        id: 127675,
        original_language: "es",
        original_title: "Los autómatas de la muerte",
        overview:
            "The evil scientist Dr. Caronte plots to revive the brains of three dead scientists and use them to obtain the formula for the super-powerful neutron bomb. The resulting creation needs blood lots of blood, sending Caronte's midget assistant Nick and his legion of mutant monsters out to get fresh victims. However, the masked atom-superman Neutron vows to put a stop to Caronte's deeds.",
        popularity: 0.6577,
        poster_path: "/kMg315Wa2RBnaHIhRHqWw6yqyrk.jpg",
        release_date: "1962-08-10",
        title: "Neutron the Atomic Superman vs. the Death Robots",
        video: false,
        vote_average: 5.3,
        vote_count: 13,
    },
    {
        adult: false,
        backdrop_path: "/o9LNQq9yxixVeIk5Y4yvEloyLaF.jpg",
        genre_ids: [16],
        id: 672375,
        original_language: "ja",
        original_title: "キン肉マン 正義超人vs古代超人",
        overview:
            "While Kinnikuman is on vacation with Mari-san's kindergarten class at Easter Island, the young wheelchair-bound Kouichi-kun laments being with an idiot like Kinnikuman, preferring to instead be with his favorite Seigi Choujin Buffaloman. Meanwhile, the other Seigi Choujins are also vacationing at ancient landmarks.",
        popularity: 0.4728,
        poster_path: "/1FGYZ8xCctRUO0Yx1aKX0FBZX9R.jpg",
        release_date: "1985-03-15",
        title: "Kinnikuman: Justice Superman vs. Ancient Superman",
        video: false,
        vote_average: 5.5,
        vote_count: 4,
    },
    {
        adult: false,
        backdrop_path: null,
        genre_ids: [],
        id: 293077,
        original_language: "fr",
        original_title: "Superman n'est pas juif (...et moi un peu)",
        overview:
            "When he finds out that it's because he's Jewish that his willy is different, young Benjamin decides to do everything he can to hide his religion and keep his secret...",
        popularity: 0.232,
        poster_path: null,
        release_date: "2014-05-30",
        title: "Superman Isn't Jewish (...But I Am a Bit)",
        video: false,
        vote_average: 2,
        vote_count: 1,
    },
    {
        adult: false,
        backdrop_path: "/2IbaHMUwb81cr7PwcvaXl0JtikP.jpg",
        genre_ids: [878, 28, 12],
        id: 41800,
        original_language: "en",
        original_title: "Superman and the Mole Men",
        overview:
            "Reporters Clark Kent and Lois Lane arrive in the small town of Silsby to witness the drilling of the world's deepest oil well. The drill, however, has penetrated the underground home of a race of small, furry people who then come to the surface at night to look around. The fact that they glow in the dark scares the townfolk, who form a mob, led by the vicious Luke Benson, intent on killing the strange people. Only Superman has a chance to prevent this tragedy.",
        popularity: 1.3397,
        poster_path: "/9vRltKcX4wK4ms0A6PbRz42EMdq.jpg",
        release_date: "1951-11-23",
        title: "Superman and the Mole Men",
        video: false,
        vote_average: 5.3,
        vote_count: 68,
    },
    {
        adult: false,
        backdrop_path: null,
        genre_ids: [28, 12],
        id: 308300,
        original_language: "hi",
        original_title: "Mr. Superman Ki Waapsi",
        overview:
            "Childless farmer Ram Dayal comes across an abandoned child, who had landed from a spaceship, takes him home to his wife, where they decide to adopt him and name him Jaikumar. When he grows up he excels in wrestling, overcoming even much older children. Then he uses his powers to discover buried treasure, which his foster father donates to the Government. Years later, Jaikumar has re-located to Bombay where he works as a Journalist with a publication called 'Azad Desh'. Using his super-powers, he is able to unearth a number of criminal conspiracies and makes phone calls as 'Mr. Superman' to Inspector Dilip Desai. Then a series of robberies take place and the police are notified by victim/complainants that the culprit is none other than the masked caped crusader himself. Watch what impact this has on Jaikumar's credibility with the police and public on one hand and with gangsters on the other.",
        popularity: 0.2859,
        poster_path: "/6WYXx7JFE0VXNEDJgn34TF63uMM.jpg",
        release_date: "1960-01-01",
        title: "Return of Mr. Superman",
        video: false,
        vote_average: 3,
        vote_count: 1,
    },
    {
        adult: false,
        backdrop_path: "/oFbqXZEjlJOCWkiQmpBK01BgHdy.jpg",
        genre_ids: [12, 80],
        id: 107181,
        original_language: "it",
        original_title: "Goldface - Il fantastico Superman",
        overview:
            "Goldface fights dr. Cobra's, aided by a bare chested African named Kotar. When Kotar's not punching folks, he's eating peanuts, bugging out his eyes, and speaking gibberish while referring to Goldy as \"B'wana\".",
        popularity: 0.5394,
        poster_path: "/A9EAN6cULwsGV3v8K6lLBjx1A1K.jpg",
        release_date: "1967-12-22",
        title: "Goldface, the Fantastic Superman",
        video: false,
        vote_average: 4.8,
        vote_count: 4,
    },
    {
        adult: false,
        backdrop_path: "/19pVEqVWadJUAbCqJ6SxXZUIyNe.jpg",
        genre_ids: [35, 14, 12],
        id: 67958,
        original_language: "ru",
        original_title: "Суперменеджер, или Мотыга судьбы",
        overview:
            "A funny fantasy about mangers, hobbits and other surprising people.",
        popularity: 2.6281,
        poster_path: "/aoDHxPAqS5G8n10NGdzXgegVMAO.jpg",
        release_date: "2011-05-19",
        title: "SuperManager, or Hack of the Fate",
        video: false,
        vote_average: 4.1,
        vote_count: 10,
    },
];
