#!/usr/bin/env sh
set -e

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

CHANGED_FILES=$(git diff --name-only origin/$CURRENT_BRANCH...HEAD)

# APPS/CLIENT

if echo "$CHANGED_FILES" | grep -q "^apps/client/"; then
  echo "📦 Modification found in apps/client"
  cd apps/client
  pnpm install
  pnpm run build
else
  echo "✅ No modification found in apps/client, skipping build"  
fi

# APPS/WORKER

if echo "$CHANGED_FILES" | grep -q "^apps/worker/"; then
  echo "📦 Modification found in apps/worker"
  cd apps/worker
  pnpm install
  #pnpm run test // Will fail locally without redis
  pnpm run build
fi

# APPS/API

if echo "$CHANGED_FILES" | grep -q "^apps/api/"; then
  echo "📦 Modification found in apps/api"
  cd apps/api
  pnpm install
  pnpm run build
fi