name: API CI
on:
    push:
        paths:
            - "apps/api/**"
    pull_request:
        paths:
            - "apps/api/**"

jobs:
    build-n-test:
        defaults:
            run:
                working-directory: apps/api
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10
                  run_install: false

            - name: Copy test env
              run: cp .env.test .env

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: pnpm install

            - name: Run Prisma generate
              run: pnpm prisma generate

            - name: Run tests
              run: pnpm test

            - name: Build project
              run: pnpm run build

    deploy:
        runs-on: ubuntu-latest
        needs: build-n-test
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Deploy to prod
              run: |
                  curl \
                  --request GET '${{ secrets.DEPLOY_URL_API }}' \
                  --header 'Authorization: Bearer ${{ secrets.DEPLOY_HOOK_SECRET }}'
